version: "3.1"
services:
    www:
        build: .
        container_name: saburo_admin_people_apache
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.4
        container_name: saburo_admin_people_mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
        volumes:
            - ./mysql:/var/lib/mysql
        networks:
            - default
    adminer:
        container_name: saburo_admin_people_adminer
        image: adminer
        ports:
            - 8080:8080

